Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "DontVTSwitch" "true"
EndSection
Section "Device"
    Identifier "BrickFramebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection
Section "Monitor"
    Identifier "BrickLCD"
EndSection
Section "Screen"
    Identifier "BrickScreen"
    Device "BrickFramebuffer"
    Monitor "BrickLCD"
EndSection
Section "ServerLayout"
    Identifier "BrickLayout"
    Screen 0 "BrickScreen"
EndSection
